server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/douyin?serverTimezone=UTC&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: HZ
  application:
    name: provide
  main:
    allow-bean-definition-overriding: true
ribbon:
  eager-load:
    clients: platform
    enabled: true
#platform:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    study.alibaba.feignClient.PlatformFeignClient: debug
feign:
  client:
    config:
      platform:
##全局default
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
